### ISSUE TITLE
วาดฉาก

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#12]
ทำฉากต่างๆ
-หน้าเริ่มต้น
-หน้าเลือกด่าน
-หน้าตัวเกม
-หน้าชนะ

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189956951-c3d37a79-1086-42b0-bc16-86ddf3765114.png)

**Comment by chananchidaily** [comment]
@Anawatratt จริงๆมันคือแบบนี้เซฟแล้วลองเอาไปแปะดูดิ้

**Comment by Anawatratt** [comment]
![IMG_2138](https://user-images.githubusercontent.com/110977191/190007008-5c628f7b-f149-466a-a9b7-7c4e59b67407.JPG)
![IMG_2139](https://user-images.githubusercontent.com/110977191/190007015-9cf567ef-d
![IMG_2135](https://user-images.githubusercontent.com/110977191/190007026-4fc63006-5bdd-438d-8ede-7acb925c6851.JPG)
535-4097-9211-f82c6e1941f6.JPG)

**Comment by Anawatratt** [comment]
![IMG_2135](https://user-images.githubusercontent.com/110977191/190007371-58809c88-cb00-499f-ac3b-674a76de4242.JPG)

**Comment by ShinRunner1st** [comment]
@Anawatratt อันไหนคือเสร็จแล้ว?

**Comment by Anawatratt** [comment]
![ปกV 1 ](https://user-images.githubusercontent.com/110977191/190065888-66856b84-01cb-4c2d-976e-22721b98cada.jpeg)

**Comment by Anawatratt** [comment]
> @Anawatratt อันไหนคือเสร็จแล้ว?
อันล่างสุดอะ อันบนๆอยากใส่ไว้ให้เห็นความคืบหน้า

**Comment by Anawatratt** [comment]
![ปกV 2+เบลอ+ปรับแสง](https://user-images.githubusercontent.com/110977191/190071101-f3a59cca-0c82-4cf9-a153-c56e1371cc5e.jpg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190113646-cd193206-202f-4297-96e1-cc1f7f6f3152.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190113758-6f1b822a-5e6d-4ff1-951c-1e4506624bf4.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190113834-ab022458-d4a2-4726-9576-eca0def32ded.png)

**Comment by chananchidaily** [comment]
![Uploading 190113897...]

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190113936-520f9403-f514-4e52-8937-8774c649dbaf.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190113974-c0d8d69d-f12b-4776-ab2f-1f5f05e524f9.png)

**Comment by chananchidaily** [comment]
![Uploading 190114018...]

**Comment by ShinRunner1st** [comment]
@chananchidaily แก้ปุ่ม ตอนเปลี่ยนสีไม่ต้องเอาตัวหนังสือออก จะได้รู้ว่าเป็นปุ่มไหน

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190138740-f4476b28-7205-46b7-9c0e-38d0858a60ad.png)

![image](https://user-images.githubusercontent.com/110966947/190138788-8f01586e-cf72-460a-8061-e98c6f9eeaca.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190138839-02335e30-e2bd-447a-8583-c3884fd2fd91.png)

![Uploading 190138857...]

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190139035-d7883b7f-e419-4928-9558-0546a1a290c0.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190139115-0177b1e5-f6c0-41bf-9006-b0f67d1ed13b.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190139167-303fd63b-fdb7-48b8-9f79-de66743f0c13.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190139215-2afc35e4-7b17-48af-995b-3f5affb913e7.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190221969-01f14738-9644-4bed-8033-b8afcebc886d.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190222075-94b31ac7-fd04-4ec1-96fb-1e5ca593ec53.jpeg)

**Comment by chananchidaily** [comment]
@Anawatratt

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895228-6e7b3d25-8ece-4a20-ab63-156a15424fe8.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895240-108f804b-9ff6-4188-8c72-04accc80923b.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895253-48152e00-31f8-4451-b36b-dc8733f0729b.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895267-3f37a17d-86e1-436e-a360-650b7078e1d9.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895308-2f7d5043-9ca4-462b-997a-91bf62f428ee.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190895604-01e5acbf-0d88-4cb5-9a70-0485e7efe1cf.jpeg)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190907734-612baf16-eab3-4c81-9d95-75825911c0e9.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190907924-531b6779-dc8f-45d9-9666-23394f804cd9.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190908254-9f15954e-a5f3-4d55-9362-00886dfde115.png)

**Comment by Winneyp** [comment]
ทำมาซะเยอะเชียว ทำไว้ให้เลือกหรอ

**Comment by Winneyp** [comment]
สวยจัดเลยแต่ละรูป

**Comment by chananchidaily** [comment]
ใช่แล้ว

ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: Winney ***@***.***>
ส่ง: Sunday, September 18, 2022 8:49:58 PM
ถึง: Winneyp/group-14 ***@***.***>
สำเนาถึง: CHANANCHIDA THAWORNWONG ***@***.***>; Mention ***@***.***>
ชื่อเรื่อง: Re: [Winneyp/group-14] วาดฉาก (Issue #12)


ทำมาซะเยอะเชียว ทำไว้ให้เลือกหรอ

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913126-fe79fb56-e5eb-41a8-ba28-84b4c35613c8.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913134-24c33708-1cff-475c-a5fb-74cc4332ad9a.png)

**Comment by Anawatratt** [comment]
โหดมากก555  สวยเลยยย

**Comment by Anawatratt** [comment]
![ปกfinal](https://user-images.githubusercontent.com/110977191/190934063-51389e41-a625-416c-9d7b-1135d3b45f5b.jpg)

**Comment by Anawatratt** [comment]
ปกใหม่เพิ่มกีตาร์กับใส่แมส จะได้ดูเข้ากับเกมเพลย์มากขึ้น
