### ISSUE TITLE
เขียนโค้ดไอเทม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#13]
เขียนโค้ดความสามารถของไอเทมในเกม
-หัวกะโหลก -50 HP
-ฮีล +20 HP
-x2 damage ดาเมจ*2 10วิ

**Comment by ShinRunner1st** [comment]
- ไอเทมลด HP
>MISS = ( -6 - ( Constant HP * 0.1 ))

- ไอเทม Heal
> PERFECT = ( 3 - ( Constant HP * 0.25 ))
 GOOD = ( 1 - ( Constant HP * 0.25 ))

- ไอเทม x2 Damage
> PERFECT = (( -300 / Total Note ) - (( 100 / Total Note ) / ( Constant HP * 0.3 ))) * 2
GOOD = (( -300 / Total Note ) - (( 100 / Total Note ) / ( Constant HP * 0.1 ))) * 2

**Comment by ShinRunner1st** [comment]
### Item percent chance

- 80% : ไม่มีไอเทม
- 10% : ไอเทม Heal
- 5% : ไอเทม x2 Damage
- 5% : ไอเทมลด HP
