### ISSUE TITLE
ทำ Engine/Mechanic ของตัวเกม ช่วง 2

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#17]
ทำเกมให้สำเร็จ
- ระบบตีบอส
- รวมระบบไอเทมเข้ากับเกม
- นำตัวละครมาใส่

**Comment by ShinRunner1st** [comment]
- [x] ระบบตีบอส
- [x] ไอเทม
- [ ] นำตัวละครมาใส่
รอ #8 Close
