### ISSUE TITLE
ข้อเสนอแนะจากอาจารย์

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#18]
ให้นำโควิดเข้ามาเป็นองค์ประกอบหลักของเกม
    -ไอเทม มีความสอดคล้องกับสถานการณ์
    - ลูกศร ให้มีธีมโควิด

**Comment by chananchidaily** [comment]
ให้นำเสนอ ในgit เลยยย แบบมีอะไรเอาภาพใส่ไว้ในนี้
