### ISSUE TITLE
แก้รูปแบบลูกศร

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#19]
ทำให้เป็นแนวโควิด

**Comment by Anawatratt** [comment]
![ลูกศร+ตัวรับฉบับปรับปรุง](https://user-images.githubusercontent.com/110977191/190099158-e0e56ce3-ced1-4c26-bf7c-fc5a0eef929c.JPG)

**Comment by Anawatratt** [comment]
![Red(final)](https://user-images.githubusercontent.com/110977191/190099196-e50ed823-57cc-428f-8cc1-b2bb29255106.png)

**Comment by Anawatratt** [comment]
![Blue(final)](https://user-images.githubusercontent.com/110977191/190099214-1e3c6baa-d970-44fd-afb3-7e2167f891e3.png)

**Comment by Anawatratt** [comment]
![Green(final)](https://user-images.githubusercontent.com/110977191/190099242-3ee50b3f-d713-41a3-b845-2b98df43aafd.png)

**Comment by Anawatratt** [comment]
![Yellow(final)](https://user-images.githubusercontent.com/110977191/190099266-c9b7f1ee-8d80-42ca-b3a8-09e613148466.png)

**Comment by Anawatratt** [comment]
![ตัวรับfinal](https://user-images.githubusercontent.com/110977191/190099309-37c6342d-d9a4-4e25-9007-81cea3c99a5c.png)

**Comment by Anawatratt** [comment]
![White(final)](https://user-images.githubusercontent.com/110977191/190109355-ddd2ec42-5f55-4b6b-a208-23ae643b51a0.png)
