### ISSUE TITLE
ออกแบบไอเทม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#20]
ให้เข้าธีมโควิด
  - ลดเลือด
  - เพิ่มเลือด
  - ดาเมจ*2

**Comment by Anawatratt** [comment]
![BlueX2](https://user-images.githubusercontent.com/110977191/190128131-b0d5813b-d9d8-4616-a64e-ef15caa53c08.png)
![GreenX2](https://user-images.githubusercontent.com/110977191/190128150-5e76534d-7af2-4797-bb8d-9c3407b184
![RedX2](https://user-images.githubusercontent.com/110977191/190128156-0b98fc77-14d2-42f1-92b1-c952bce9fa17.png)
aa.png)
![YellowX2](https://user-images.githubusercontent.com/110977191/190128165-3dafec48-0d95-4fb9-98ab-b62bfafe9006.png)

**Comment by Anawatratt** [comment]
![kill1](https://user-images.githubusercontent.com/110977191/190128380-14cb29b0-f0de-4725-abc7-15f1449334fb.png)
![kill2](https://user-images.githubusercontent.com/110977191/190128390-939b73e9-5f3c-4b3e-9607-ec465e59374e.png)

**Comment by Anawatratt** [comment]
![Heal](https://user-images.githubusercontent.com/110977191/190128429-e1e9e751-62ba-4afe-96bb-7fd506cea5cd.png)

**Comment by Anawatratt** [comment]
-วัคซีน เป็นยาฮีล
-ตัวไวรัสสีดำคือตัวลดเลือด (ทำมา2แบบ คือเขียวและเทาเลือกเอาไปใช้เลย)
-แมสทำมา4 สี เป็นx2 เพราะคิดว่าเพิ่มประสิทธิภาพในการสู้กับไวรัสไรงี้

**Comment by Anawatratt** [comment]
![Kill3](https://user-images.githubusercontent.com/110977191/190245644-7aed61bb-1943-4dcc-9beb-a19fc4a3b519.png)

**Comment by Anawatratt** [comment]
![RedX2V white](https://user-images.githubusercontent.com/110977191/190257262-b7ec5daf-4770-4a2a-8031-22cc33eeeca2.png)
![YellowX2V white](https://user-images.githubusercontent.com/110977191/190257271-3a444820-0e67-4ca5-9eb8-ad2c1da5cba6.png)

**Comment by Anawatratt** [comment]
![BlueX2V white](https://user-images.githubusercontent.com/110977191/190257289-aca62054-fa4f-497f-bf25-b21824ad3c6d.png)
![GreenX2V white](https://user-images.githubusercontent.com/110977191/190257299-94d2a00c-8814-4b66-a5c5-6cd896416720.png)

**Comment by Anawatratt** [comment]
![HealV white](https://user-images.githubusercontent.com/110977191/190257350-0cce506e-e038-4d6f-a764-c98837772292.png)

**Comment by Anawatratt** [comment]
![HealV white](https://user-images.githubusercontent.com/110977191/190257415-4302847a-64f7-4d96-9b6c-4251c39ffb9f.png)

**Comment by Anawatratt** [comment]
![Kill4](https://user-images.githubusercontent.com/110977191/190257468-52ead373-207b-48d4-a370-4c9847b0e1db.png)

**Comment by Anawatratt** [comment]
ทำเป็นพื้นหลังขาวหมดแล้ว @ShinRunner1st
