### ISSUE TITLE
ออกแบบหน้าต่างตั้งค่า

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#21]
- กรอบหน้า setting
- ตัวเลือกต่าง เช่น ลดเสียง ตั้งค่าเสียง ตั้งค่าปุ่ม

**Comment by ShinRunner1st** [comment]
หน้าจอตอนที่ยังไม่ได้แก้
![chrome_CTtdiWwMc6](https://user-images.githubusercontent.com/98098151/190110340-d3890dff-e9fd-4681-b6c7-0fdd8b0a5089.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476564-e271d9aa-968d-48a3-b92c-6f37115c2933.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476579-c64d13b9-fea7-4b3b-8189-d77e21b9e0db.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476609-d403fb42-8024-4fe2-889c-e2a5fa830c05.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476635-6abed5c8-e2b7-4237-9c80-bb3d5f02c704.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476723-501e72e6-73bb-4428-8cd0-4904c1c12314.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190476780-774cedc3-f739-4383-8c28-f0512e082001.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190477526-9e310680-3461-43ec-aa4e-9163786b9dd0.png)

**Comment by ShinRunner1st** [comment]
@chananchidaily ปุ่มสลับโหมดเปลี่ยนชื่อเป็นอย่างอื่นได้ไหม เอาเป็นอันนึงเขียน"ผ่านด่าน"กับ"Freeplay"

**Comment by ShinRunner1st** [comment]
หน้าต่างตั้งค่าตอนนี้
> **หน้าที่ 1**
>- ปุ่มปรับเสียง เพลง
>- ปุ่มปรับเสียง เอฟเฟค
>- ปุ่มเปลี่ยนโหมด กลางวัน - กลางคืน
>![chrome_kqyCueHKqg](https://user-images.githubusercontent.com/98098151/190635417-c929e3bd-f48f-40a6-888c-36449baf9ab2.png)

> **หน้าที่ 2**
>- เปลี่ยน สกิน รูปแบบโน็ต
>![chrome_eIx28zieSQ](https://user-images.githubusercontent.com/98098151/190635631-9a93ece6-04b0-4bdb-8fe5-372a888b58c5.png)

> **หน้าที่ 3**
>- ปุ่มตั้งค่า ปุ่มกด
>![chrome_TfG7hzzJFF](https://user-images.githubusercontent.com/98098151/190635862-12660577-4730-4782-950f-b91ce3294d6a.png)

> **หน้าที่ 4**
>- ตั้งค่าความเร็วของโน็ต สามารถดูความเร็วได้แบบ เรียลไทม์
>![chrome_ZgwWhRU00G](https://user-images.githubusercontent.com/98098151/190635876-2d52b342-4b38-450e-a540-5b98c70a5ccf.png)

อยาก ปรับเปลี่ยน หรือ เพิ่ม ตรงส่วนไหน คอมเม้นได้

@chananchidaily รีเควส ปุ่ม เปลี่ยนโหมด กลางวัน-กลางคืน หน่อย อยากให้มันสวยๆกว่านี้

**Comment by ShinRunner1st** [comment]
@chananchidaily เปลี่ยนชื่อ ปุ่ม "music volume" "effect volume" เป็นภาษาไทยหน่อย
