### ISSUE TITLE
พื้นหลังปุ่มเลือกด่าน

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#22]
ทำพื้นหลังปุ่มเลือกด่าน(แค่พื้นหลังตัวเลขไม่ต้อง) 
สูงพอประมาณ ยาวครึ่งจอ

**Comment by ShinRunner1st** [comment]
พื้นหลังแบบเก่า
![menu-button-background@2x](https://user-images.githubusercontent.com/98098151/190162157-73b29384-9796-4857-a5ce-c626ca88a835.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913152-c4c1e4ca-64ef-4d3f-aefa-9ca5ca15bfd9.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913213-f7445f63-1f9e-4d72-af75-75915a99bcf3.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913329-e88e0fc0-8518-4598-a722-2bd8fae26b5e.png)

**Comment by ShinRunner1st** [comment]
> ![image](https://user-images.githubusercontent.com/110966947/190913329-e88e0fc0-8518-4598-a722-2bd8fae26b5e.png)

มาเป็นแท่งเลย 5555

แล้วเอาอันไหนดีอะ

**Comment by chananchidaily** [comment]
อันที่ชอบเลย55555555555555555

ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: ShinRunner1st ***@***.***>
ส่ง: Sunday, September 18, 2022 10:12:59 PM
ถึง: Winneyp/group-14 ***@***.***>
สำเนาถึง: CHANANCHIDA THAWORNWONG ***@***.***>; Comment ***@***.***>
ชื่อเรื่อง: Re: [Winneyp/group-14] พื้นหลังปุ่มเลือกด่าน (Issue #22)


[image]<https://user-images.githubusercontent.com/110966947/190913329-e88e0fc0-8518-4598-a722-2bd8fae26b5e.png>

มาเป็นแท่งเลย 5555

แล้วเอาอันไหนดีอะ

**Comment by ShinRunner1st** [comment]
เอาแท่ง สีเนื้อ ละกันเนอะ 555
