### ISSUE TITLE
ฉากตอนตาย

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#23]
ฉากตอนตาย
- ปุ่มเริ่มใหม่
- ปุ่มกลับหน้าหลัก

**Comment by ShinRunner1st** [comment]
>**ตอนนี้**
>![chrome_jGQZRIg29u](https://user-images.githubusercontent.com/98098151/190784193-7d756dcd-9065-49ce-82cd-d4eaa9ac506d.png)
**ยืมรูป+ปุ่มมาจากเกมอื่น**

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913226-1a2b5bc5-47f1-4801-9adf-4a70482c2ebb.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913238-7c111850-a405-49a2-9418-d227b786deed.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913246-80095600-9d3b-49c2-9c02-b9556fee1371.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913253-5132bd10-62c5-46b3-96e4-dc16c3853c4a.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/190913267-c436a29d-ef19-4355-ae16-28b599ad13da.png)
