### ISSUE TITLE
แก้ UI กดเบิ้ล

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#24]
[บัคหน้าUI](https://youtu.be/xFqQdVLSp2w)

แก้ UI หน้าตั้งค่าปุ่ม 

- [x] ถ้ากดย้ำหลายครั้งจะมีหน้าต่างถามหลายครั้งขึ้นมา
- [x] ไม่มีการตั้งปุ่มออกฉุกเฉินขณะเล่นเกม
- [x] UI สลับโหมดควรมีข้อความบอกโหมดขณะนั้น

**Comment by ShinRunner1st** [comment]
> ถ้ากดย้ำหลายครั้งจะมีหน้าต่างถามหลายครั้งขึ้นมา
- แก้แล้ว
> ไม่มีการตั้งปุ่มออกฉุกเฉินขณะเล่นเกม
- เพิ่มแล้วแต่ปุ่มยังไม่ค่อยมีความสวยงาม
> UI สลับโหมดควรมีข้อความบอกโหมดขณะนั้น
- เพิ่มแล้ว
