### ISSUE TITLE
แก้ด่านที่1

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#25]
https://youtu.be/Ku0T-tlRwKY

- [x] ไอเทมลงมาถี่เกินไป
- [x] เมื่อกดได้ไอเกมควรมีอะไรให้เห็น (เช่น เอฟเฟค ตัวอักษร เวลาจะหมดของไอเทม)
- [x] เกมจบไว้เกินไป
- [x] ไอเทมมีผลกับตัวเองค่อนข้างน้อย (ฮีลน้อย ความเสียหายจากไอเทมต่อผู้เล่นน้อย)
- [x] ควรทำให้เอเทมใหญ่กว่านี้ (เพิ่มขนาด &สีพื้นหลังให้มีออร่า)

**Comment by ShinRunner1st** [comment]
> ไอเทมลงมาถี่เกินไป
- #13 เปอร์เซนต์การออกไอเทม ตามนี้
> เมื่อกดได้ไอเกมควรมีอะไรให้เห็น (เช่น เอฟเฟค ตัวอักษร เวลาจะหมดของไอเทม)
- อาจะต้องขอ @chananchidaily @Anawatratt ทำเอฟเฟค ส่วนไอเทม จะไม่มีเวลาหมด แต่ เป็นการใช้ทันที
> เกมจบไว้เกินไป
- แก้ให้ทำดาเมทต่อบอส "ยากขึ้น" กับ เปลี่ยนเพลงแล้ว รออัพเดท หน้า
> ไอเทมมีผลกับตัวเองค่อนข้างน้อย (ฮีลน้อย ความเสียหายจากไอเทมต่อผู้เล่นน้อย)
- แก้ สมการไอเทมฮีล จาก `PERFECT = ( 5 - ( Constant HP * 0.25 ))` `GOOD = ( 3 - ( Constant HP * 0.25 ))` 
เป็น `PERFECT = ( 15 - ( Constant HP * 0.25 ))` `GOOD = ( 12 - ( Constant HP * 0.25 ))` 
- ไอเทมลดเลือด จาก `MISS = ( -6 - ( Constant HP * 0.1 ))` 
เป็น `MISS = ( -30 - ( Constant HP * 0.1 ))` โดยที่ปกติ `Constant HP = 7`
> ควรทำให้ไอเทมใหญ่กว่านี้ (เพิ่มขนาด &สีพื้นหลังให้มีออร่า)
- @chananchidaily @Anawatratt เบื้องต้น แก้โดยการเพิ่มขนาดแล้ว รออัพเดทหน้า

**Comment by ShinRunner1st** [comment]
เพิ่มเติม
- เปลี่ยนจาก บอสเลือดหมด แล้วจบเกมเป็น  บอสเลือดหมด แล้ว สามารถทำ คะแนน ต่อจนจบเพลงได้ ( Overkill ) โดยที่ถ้าบอสตายแล้ว ถ้ากดโดน ไอเทมลดเลือด หรือ กดไม่โดน จะไม่เสียเลือดจนจบเพลง

**Comment by ShinRunner1st** [comment]
> เพิ่มเติม
> 
> * เปลี่ยนจาก บอสเลือดหมด แล้วจบเกมเป็น  บอสเลือดหมด แล้ว สามารถทำ คะแนน ต่อจนจบเพลงได้ ( Overkill ) โดยที่ถ้าบอสตายแล้ว ถ้ากดโดน ไอเทมลดเลือด หรือ กดไม่โดน จะไม่เสียเลือดจนจบเพลง

เอาออกละ
