### ISSUE TITLE
แก้ UI เปลี่ยนโควิดเป็นลูกศร

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#27]
https://user-images.githubusercontent.com/72338812/190900673-044c4ac3-d7be-4889-a3ec-191b05780dd0.mp4

เฉพาะในโหมดผ่านด่าน
-เปลี่ยนโควิดเป็นลูกศรแล้วไอคอนไม่เปลี่ยนตาม
-หรือถ้าจะไม่ให้ผู้เล่นเปลี่ยนจากโควิดเป็นลูกศรก็ให้เอาปุ่มสลับไอคอนออกเมื่อเปลี่ยนเป็นโหมดผ่านด่านแล้ว

**Comment by ShinRunner1st** [comment]
- ผู้เล่นจะโดนบังคับใช้ ปุ่มโควิด ในโหมด ผ่านด่าน แต่ถ้าไม่อยากให้กดเปลี่ยนได้จริวๆ จะเอาไอคอน ปุ่มโควิด ออกให้พิมคอมเม้นต์มาเลย

**Comment by Winneyp** [comment]
ถ้ามาโหมดผ่านด่านแล้วเอาปุ่มออกเลย

**Comment by ShinRunner1st** [comment]
โอเค
