### ISSUE TITLE
บอสตายแล้วเกมไม่จบ

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#28]
https://youtu.be/4cxR0TWvHVc

HP บอสหมดแล้วแต่เกมยังไม่จบ

**Comment by ShinRunner1st** [comment]
> HP บอสหมดแล้วแต่เกมยังไม่จบ
- #25 อ่านก่อน หรือว่า อยากจะทำให้บอสตายแล้วจบเกม ถ้าทำแบบนั้นเกมจะ จบเร็วไปนะ

**Comment by ShinRunner1st** [comment]
ไม่ได้ Bug แต่เป็น Feature ใหม่

**Comment by Winneyp** [comment]
มันก็จะเหมือนด่านที่ไม่มีบอสนะถ้างั้นอะ

**Comment by ShinRunner1st** [comment]
งั้นก็แลกกับเกมจบไว้เนอะ ถ้าโอเคก็จะ Close ละนะ

**Comment by Winneyp** [comment]
เวลามันก็โอเคอยู่นะ มันด่านแรกเองหนิ

**Comment by ShinRunner1st** [comment]
โอเคงั้นแก้ให้เป็นเหมือนเดิมละ
