### ISSUE TITLE
จบเพลงแต่บอสไม่ตาย

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#29]
https://youtu.be/mCRb2YpXLyM

ลองทดสอบว่าถ้าประคองเลือดบอสกับผู้เล่นไปจนจบเพลงโดยที่บอสไม่ตาย
- ผู้เล่นจะเป็นฝ่ายชนะ
- แก้ให้มีเงื่อไขว่าถ้าบอสไม่ตายจะแพ้

**Comment by ShinRunner1st** [comment]
แก้แล้ว
