### ISSUE TITLE
ความถี่การออกไอเทมเยอะ

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#30]
https://youtu.be/HbU-HkLkX0M

ครั้งที่1 (00:56-02:35)

-  ไอเทมฮีล 15 
 - ไอเทมคูณสอง 11

ครั้งที่2 (2:43-4:19)
 - ไอเทมฮีล 16 
 - ไอเทมคูณสอง 7

**Comment by ShinRunner1st** [comment]
- #13 เปอร์เซนต์การออกไอเทมตามนี้
`80% : ไม่มีไอเทม`
`10% : ไอเทม Heal`
`5% : ไอเทม x2 Damage`
`5% : ไอเทมลด HP`
จะให้เปลี่ยนเท่าไหร่เขียนมาเลย

**Comment by Winneyp** [comment]
88
5
2
5
แล้วเดี๋ยวขอเทสใหม่

**Comment by ShinRunner1st** [comment]
รีเฟซดูถ้าเป็น v1.7.2 ก็แก้ละ

**Comment by Winneyp** [comment]
ความถี่ไอเทมโอเคละ
