### ISSUE TITLE
สิ่งที่อยากให้เพิ่ม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#32]
- [x] สตอรี่ของเกม ให้มาเกลิ่นตอนกดเริ่มเกม และตอนจบเกม
![image](https://user-images.githubusercontent.com/72338812/190903343-24373701-65cb-495d-8170-b98795a3a618.png)
ภาพประกอบ

- [x] ก่อนเข้าทุกครั้งอยากให้มีการอธิบายไอเทมว่าแต่ละอย่างทำไรได้บ้าง ประมาณรูปข้างล่าง
![image](https://user-images.githubusercontent.com/72338812/190903615-c5b5ab9a-6692-4eb8-afde-50808e88aeed.png)

**Comment by Anawatratt** [comment]
![1](https://user-images.githubusercontent.com/110977191/191273564-325ac685-0f04-4a63-876a-c7b8e17abad6.png)
![2](https://user-images.githubusercontent.com/110977191/191273580-16334fb5-a058-4ceb-a773-5a9138413899.png)
![3](https://user-images.githubusercontent.com/110977191/191273599-be6b8a65-b192-4a39-a1c9-9df986a36ee8.png)
![4](https://user-images.githubusercontent.com/110977191/191273604-7471870d-6e6c-418b-93cc-8e83f7322803.png)
![5](https://user-images.githubusercontent.com/110977191/191273673-92968eba-56e0-4985-9270-b21beef5e2a3.png)
![6](https://user-images.githubusercontent.com/110977191/191273626-52bd277e-877d-4192-bc27-68437a3ef76e.png)
![7](https://user-images.githubusercontent.com/110977191/191273712-05bb6e7b-bedf-4c89-935e-443aac60bc3c.png)
![8](https://user-images.githubusercontent.com/110977191/191273743-ec5c0833-a7ba-4c45-a046-ea1f28ffc07c.png)
![9](https://user-images.githubusercontent.com/110977191/191273770-21d5193b-a304-45ed-97ef-30db1a0f21f8.png)
![10](https://user-images.githubusercontent.com/110977191/191273790-4752eadc-c0fc-4c5a-80eb-998c1aae4c4c.png)
![11](https://user-images.githubusercontent.com/110977191/191273812-0fc0999b-f7a0-4d83-939f-0f1dd5770bcf.png)

**Comment by Anawatratt** [comment]
![12](https://user-images.githubusercontent.com/110977191/191304590-e47fe303-a485-4b01-ae34-0ad35836833c.png)
![13](https://user-images.githubusercontent.com/110977191/191304601-4b44edef-afc4-4051-839c-550e27b07c8a.png)
![14](https://user-images.githubusercontent.com/110977191/191304608-11e6c8e0-3136-460b-a13a-ca72ac5c804a.png)
![15](https://user-images.githubusercontent.com/110977191/191304626-22dd1fb5-c1fb-48f5-a788-0c74a337d659.png)
![16](https://user-images.githubusercontent.com/110977191/191304638-c45f36bd-a397-440c-a402-0de2527afd26.png)
![17](https://user-images.githubusercontent.com/110977191/191304646-b7483c90-018a-49b7-9be2-f790c329310a.png)
![18](https://user-images.githubusercontent.com/110977191/191304651-709cdf0d-35f7-4b3d-8b93-05839b15e0fa.png)
ส่วนตอนจบ
