### ISSUE TITLE
งานที่เหลือของdesign

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#33]
ตอนนี้งานดีไซน์เหลือ
- [x] แก้สีผมตัวละครหลักตอนตาย
- [x] ปุ่มUIตอนตาย
- [x] พื้นหลังปุ่มเลือกด่าน
- [x] ตัวละครฝั่งร้าย
- [x] หน้าแนะนำไอเทม
- [x] สตอรี่ตอนเริ่มเกม
- [x] สตอรี่ตอนจบ/หน้าชนะ

**Comment by Anawatratt** [comment]
![คำแนะนำไอเทม](https://user-images.githubusercontent.com/110977191/190918952-57cbc2e9-0df4-4718-bffc-7b79f2ca58c9.png)

**Comment by Anawatratt** [comment]
> ตอนนี้งานดีไซน์เหลือ
> 
> * [x]  แก้สีผมตัวละครหลักตอนตาย
> * [x]  ปุ่มUIตอนตาย
> * [x]  พื้นหลังปุ่มเลือกด่าน
> * [x]  ตัวละครฝั่งร้าย
> * [x]  หน้าแนะนำไอเทม
> * [ ]  สตอรี่ตอนเริ่มเกม
> * [ ]  สตอรี่ตอนจบ/หน้าชนะ

สตอรี่ตอนเริ่มเกม กับจบอะเข้าใจนะ แต่หน้าชนะนี้ขอรายละเอียดมั้ยไว้มันอยู่ในฉากไหน

**Comment by ShinRunner1st** [comment]
น่าจะให้เลือกว่าจะเอาอย่างไหน หรือเปล่า ถ้าเข้าใจไม่ผิดนะ

**Comment by Anawatratt** [comment]
![1](https://user-images.githubusercontent.com/110977191/190933542-de212e2a-e820-4461-b2e5-2f905814d849.png)
![2](https://user-images.githubusercontent.com/110977191/190933544-9c726af7-1531-46dc-b646-868aa3c13c33.png)
![3](https://user-images.githubusercontent.com/110977191/190933545-2015982b-13d0-4201-8d22-58592228ff61.png)
![4](https://user-images.githubusercontent.com/110977191/190933549-b9de5b4c-f46a-43ba-9bc1-5e251072ef44.jpg)

**Comment by Anawatratt** [comment]
![5](https://user-images.githubusercontent.com/110977191/190933556-5860cf19-3265-47ba-885b-f140d7c25b9c.png)
![6](https://user-images.githubusercontent.com/110977191/190933566-a1ba30fb-aec6-4eb2-9877-fe5f952622e0.png)
![7](https://user-images.githubusercontent.com/110977191/190933568-28e24863-508f-45fc-a9c8-8048f4dfe48e.png)
![8](https://user-images.githubusercontent.com/110977191/190933571-90d56714-e4f4-4846-9903-6177c1697bb8.png)

**Comment by Anawatratt** [comment]
![10](https://user-images.githubusercontent.com/110977191/190933582-2923e561-ffa2-4a1d-9167-f3da56af9f64.png)
![11](https://user-images.githubusercontent.com/110977191/190933584-f4d8afe7-74e4-41f8-b4c0-143b7f748caa.jpg)
![12](https://user-images.githubusercontent.com/110977191/190933587-875e99e2-2333-4676-8a40-4
![13](https://user-images.githubusercontent.com/110977191/190933592-3f8b8200-5975-4d2b-8f07-8bf2469de427.png)
8f0000863aa.png)

**Comment by Anawatratt** [comment]
เรียบร้อยเวลานอนข้าพเจ้า555555 อาบน้ำกินข้าวเสร็จเรียนเลย

**Comment by ShinRunner1st** [comment]
เทพเกิน 555

- สตอรี่ตอนเริ่มเกมจะวางไว้ หลังจากที่กด เริ่มเกมครั้งแรก นะ
- ส่วนสตอรี่ตอนจบเกมจะวางไว้ หลังจากเคลียร์ด่านที่ 3 แล้วก็กด ออกมาจากหน้า leaderboard นะ

คิดว่าไงบ้าง คือตอนนี้วางโครงสร้างไว้รอละ เดี๋ยวทำอนิเมชั่นให้ด้วย

**Comment by ShinRunner1st** [comment]
ทำไมขนาดของรูปมันลดลงเรื่อยๆอะ 555 หน้าจอเกมมัน เป็น 480x360 (4:3) นะอย่าลืม ถ้ามันเกินขอบมันก็จะไม่มีส่วนนั้นนะ

**Comment by Anawatratt** [comment]
![รุปเกม1](https://user-images.githubusercontent.com/110977191/191386010-44accd09-d7a4-414d-aa78-3aa06b503e8a.png)
![รูปเกม3](https://user-images.githubusercontent.com/110977191/191386018-7b0fbadd-6352-4196-a240-2c54fc46a4f0.png)
![รูปเกม2](https://user-images.githubusercontent.com/110977191/191386022-5710ffe6-310d-4c73-aee3-511211cd6c28.png)
แปะไว้ใช้ทำ wiki

**Comment by Anawatratt** [comment]
![รูปเกม4](https://user-images.githubusercontent.com/110977191/191387344-a919e3ee-5632-4816-ab46-0122ec896779.png)
