### ISSUE TITLE
ย้ายหน้าแนะนำไอเทม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#35]
![image](https://user-images.githubusercontent.com/72338812/191410819-3edc87a8-ef6d-489a-923c-cfd2469968c3.png)

อยากให้ย้ายหน้าต่างแนะนำไอเทมไปไว้หลังจากกดเลือกด่านทุกด่าน

**Comment by ShinRunner1st** [comment]
แก้แล้ว
- โชว์ในหน้าเลือกด่านหลังจากดูสตอรี่จบครั้งแรก + เพิ่มปุ่ม ในหน้าเลือกด่าน
