### ISSUE TITLE
ทำ UI ในเกม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#6]
ทำUIในหัวข้อต่อไปนี้
1. ปุ่มstart
2. ปุ่มออกเกม
3. แถบเลือกด่าน

> ทำเสร็จแนบรูปส่งไว้ในคอมเมนต์

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089226-aa49092e-b14d-4c90-824d-ac3494e49e20.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089285-d0ee25fa-0a84-420c-a98e-cc83aa151a8d.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089398-bba6e569-345f-4d81-9753-441d8829bb99.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089652-aca14efa-807c-41d4-9849-afa4303caa9b.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089760-38deb82b-4afe-4c95-8053-6cd7cd1c2854.png)

**Comment by chananchidaily** [comment]
![Uploading 189089814...]

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189089899-f0c6e720-726c-41f1-8a63-5b040a44d70e.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189118711-ac953906-d6aa-4c13-83c0-82c2c25deebd.png)

**Comment by chananchidaily** [comment]
> ![image](https://user-images.githubusercontent.com/110966947/189080438-e73baf6e-97ad-4fb6-befb-424c1680b445.png)

![image](https://user-images.githubusercontent.com/110966947/189118900-2f6227e8-262d-4645-a995-98add0d9ab65.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177068-24c8b805-8a27-4243-8c9c-ad81c254424e.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177124-33d20f7c-d320-4ab6-b3a5-1b0002742529.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177199-d640a08a-29c8-4cfb-94df-2811aa45e451.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177252-df0434ae-b1ab-433d-bf22-05cbbaf3cf82.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177327-dec0ea5e-b7fe-459a-b307-abd5e2dbf4d9.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177369-3c31d630-dcf4-4642-8eba-8f24605db657.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177418-30cd353b-a5a3-4340-a2fc-82b0e4aa31b0.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177476-c88b2924-a840-4e45-8c86-fee2019b8766.png)

**Comment by chananchidaily** [comment]
![image](https://user-images.githubusercontent.com/110966947/189177537-4d6ff22f-700d-4cb5-9ee3-dbd1c3e3fda4.png)

**Comment by chananchidaily** [comment]
หน้าเปลี่ยนด่านๆๆๆๆ![image](https://user-images.githubusercontent.com/110966947/189178167-07df8f10-1209-4333-ac65-fa580ec554ab.png)
