### ISSUE TITLE
ทำตัวละคร&อนิเมชั้น

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#8]
-ทำตัวละครตัวร้ายและตัวดี
-ลงสีตัวละคร

ทำอนิเมชั่นของตัวละคร ประกอบด้วย
-ท่าโจมตี
-ท่าโดนดาเมจ
-ท่าชนะ 
-ท่าแพ้
#ทำทั้ง2ตัวละคร ตัวร้ายและตัวเอก

**Comment by Anawatratt** [comment]
![ท่าเบสิค](https://user-images.githubusercontent.com/110977191/190283113-572b56a9-ab78-432c-8477-94432266850d.png)

**Comment by Anawatratt** [comment]
![ท่าโจมตี1](https://user-images.githubusercontent.com/110977191/190283131-58f17c93-0f80-4079-a673-065075fe348a.png)
![ท่าโจมตี2](https://user-images.githubusercontent.com/110977191/190283136-181bd1b7-797d-4948-b839-ffae936da291.png)

**Comment by Anawatratt** [comment]
![ท่ารับดาเมจ](https://user-images.githubusercontent.com/110977191/190283152-21c2b155-81dc-4626-bd11-7053b9f093fa.png)
![ท่าตาย](https://user-images.githubusercontent.com/110977191/190283155-4ca6b612-d4ac-4f19-a04d-2b4a635966ba.png)

**Comment by Anawatratt** [comment]
![ชื่อท่าV 1](https://user-images.githubusercontent.com/110977191/190283293-23716490-2e34-49e8-8105-44d6fbb248aa.png)
รูปอธิบาย ท่า

**Comment by ShinRunner1st** [comment]
เพิ่มในเกมเรียบร้อย

**Comment by ShinRunner1st** [comment]
>หน้าจอในตอนนี้
>![chrome_KALWNxhYAG](https://user-images.githubusercontent.com/98098151/190801711-a0cd624c-9e36-4fbd-8a2b-722fa0d24ed9.png)

เพิ่มเติมตรงไหนบอกได้

**Comment by ShinRunner1st** [comment]
> ![ท่ารับดาเมจ](https://user-images.githubusercontent.com/110977191/190283152-21c2b155-81dc-4626-bd11-7053b9f093fa.png) ![ท่าตาย](https://user-images.githubusercontent.com/110977191/190283155-4ca6b612-d4ac-4f19-a04d-2b4a635966ba.png)

ขอท่าตายใหม่ ในรูปสีผมหาย

**Comment by ShinRunner1st** [comment]
ขาดตัวร้าย กับ แก้รูปแตอนแพ้

**Comment by Anawatratt** [comment]
โอเคแปปนะ555

**Comment by Anawatratt** [comment]
![1 atk](https://user-images.githubusercontent.com/110977191/190911649-5bc9db37-5de3-45ea-ba19-01845c8b59d4.png)
![1 death](https://user-images.githubusercontent.com/110977191/190911653-fa81f628-5733-4bbb-bd03-e444c6770f6e.png)
![1 hurt](https://user-images.githubusercontent.com/110977191/190911654-c24aee47-7163-42f9-9957-578e3212d846.png)
![1 stand](https://user-images.githubusercontent.com/110977191/190911658-7c4b87bf-5d47-49a6-a1ff-1962e2eeb6a7.png)

**Comment by Anawatratt** [comment]
![2 atk](https://user-images.githubusercontent.com/110977191/190911674-5e5f4f54-8019-43fb-8355-ba9548a04268.png)
![2 death](https://user-images.githubusercontent.com/110977191/190911683-fcc4212a-fbfc-480b-bac1-b87be262936a.png)
![2 hurt](https://user-images.githubusercontent.com/110977191/190911688-0b252f07-dcab-428c-a008-bae3a4769c93.png)
![2 stand](https://user-images.githubusercontent.com/110977191/190911691-88c7b58d-2c00-4033-89a0-300b51ca4d38.png)

**Comment by Anawatratt** [comment]
![3 atk](https://user-images.githubusercontent.com/110977191/190911705-5d242634-620f-457d-af8d-317df0868172.png)
![3 death](https://user-images.githubusercontent.com/110977191/190911708-6a88d632-3caf-409b-892f-fc1dcd80a694.png)
![3 hurt](https://user-images.githubusercontent.com/110977191/190911709-3a5a9386-8f96-49d6-8722-66ccff1ed194.png)
![3 stand](https://user-images.githubusercontent.com/110977191/190911711-0e170bf8-4c1d-4a9c-8f73-7027beccac94.png)

**Comment by Anawatratt** [comment]
![image](https://user-images.githubusercontent.com/110977191/190911723-cbaca948-f83c-4d3f-87d5-5f41da40bf0e.png)
คำอธิบายภาพ

**Comment by Anawatratt** [comment]
> > ![ท่าตาย](https://user-images.githubusercontent.com/110977191/190283155-4ca6b612-d4ac-4f19-a04d-2b4a635966ba.png)
> 
> @Anawatratt ขอท่าตายใหม่ ในรูปสีผมหาย
![ท่าตาย](https://user-images.githubusercontent.com/110977191/190912195-d16d2220-c1f4-4457-8ac1-fe0b6888d5c6.png)

**Comment by ShinRunner1st** [comment]
>![1 death](https://user-images.githubusercontent.com/110977191/190911653-fa81f628-5733-4bbb-bd03-e444c6770f6e.png)
รูปนี้มีขอบดำดิดมา @Anawatratt

**Comment by ShinRunner1st** [comment]
@Anawatratt คือมันเกี่ยวกับโควิด แล้วก็ทีมของเกมยังไงอะ กลัวอาจารย์ถาม

**Comment by Anawatratt** [comment]
> @Anawatratt คือมันเกี่ยวกับโควิด แล้วก็ทีมของเกมยังไงอะ กลัวอาจารย์ถาม
แค่ลูกศร กับไอเทมก็พอแล้วม้าง ใจจริงเราลองให้มันเข้าทีมโควิดแล้วแต่ มันไม่สวยเลยลบๆทำใหม่เป็น10 ตัวจนตัดใจละ555
อนิเมชั่นมันทำยากอะ ให้เค้าทีมด้วย มีหลายท่าด้วยไม่ไหว ขอไปทำส่วนอื่นก่อนไว้เกมเสร็จค่อยมาใส่ใจรายละเอียดเล็กๆใหม่

**Comment by ShinRunner1st** [comment]
โอเค เอา Designer ว่า 5555
