### ISSUE TITLE
ทดสอบmachanicเกม

### ISSUE THREAD

**Issue by Winneyp** [Winneyp/group-14#9]
ทดสอบระบบการเล่นที่ทำไว้
*พยายามทำอะไรที่นอกเหนือหลักของเกม

**Comment by chananchidaily** [comment]
เกมมีความไวเกินไปนิดนึง อาจจะทำให้เล่นยาก

**Comment by Anawatratt** [comment]
โอเคดี น่าจะปรับขนาดลูกศรไม่ก็ปรับความเร็วเกมสักนิดนึงเริ่มมาน่าจะเอาง่ายๆหน่อย แล้วก็มีปุ่มRestart ก็ดีนะ555

**Comment by chananchidaily** [comment]
ทดสอบหน้า UI (1)
- ระบบตั้งค่าหากกดหลายครั้ง
- ไม่มีปุ่มออกระบบตั้งค่า
- หากไม่ได้ตั้งค่าปุ่มที่ใช้ในเกม จะไม่สามารถเล่นเกมได้
- ตอนตั้งปุ่มที่ใช้เล่นมีความงงเกินไป (ไม่รู้ว่าInput 1 2 3 4 คือปุ่มไหน)
